language: node_js
node_js:
  'node'

addons:
  apt:
    packages:
    - libcairo2-dev
    - libjpeg-dev
    - libgif-dev

script:
- npm run test:unit
- npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_KEY
  keep-history: false
  local-dir: '/dist'
  on:
    branch: dev
